### PR TITLE
Update contributors_to_exclude list

### PR DESCRIPTION
**Pull request by mgblythe**

### CODE REVIEW

**Comment by sudeepku** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[powerapps-docs/docfx.json](https://github.com/mgblythe/powerapps-docs-pr/blob/mb-settings/powerapps-docs/docfx.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C12%5C6%5Cf1db111a-32d3-53c6-e514-6b2c2a103d47%5CPullRequest%5C201712062225222125-88%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=G6pKbrSr522Z%2F1l6XEn%2BJ%2FqELicOxVuQHUGm%2FXjhkT8%3D&st=2017-12-06T22%3A21%3A58Z&se=2018-01-06T22%3A26%3A58Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by PRMerger12** [comment]
## PRMerger Results
 | Issue | Resolution |
 --- | --- | 
 Unapproved file extension(s) |  This PR contains file types that are not supported in the repo. The only supported file types are jpg, gif, png, and md.

**Comment by mgblythe** [comment]
#sign-off

**Comment by Lisaco88** [comment]
No issues; merging now.

**Pull request merged**
