### PR TITLE
C9216: Inconsistent serial number

### PR DESCRIPTION
**Pull request by carolinacmoravia**
Hello, @mgblythe, 

Localization team has reported source content issue that causes localized version to have different format compared to en-us version.  

Please, help to check my proposed file change into the article and help to merge if you agree with fix. If not, please, let me know either if you would like me to fix it in another way within this PR, if you prefer to fix it in another PR or if I should close this PR as by-design. In case of using another PR, please, let me know of your PR number, so we can confirm and close this PR. 

Many thanks in advance.

### CODE REVIEW

**Comment by mgblythe** [comment]
Close and reopen to trigger validation

**Comment by mgblythe** [comment]
#sign-off

**Comment by Lisaco88** [comment]
In review.

**Comment by Lisaco88** [comment]
No issues; merging now.

**Pull request merged**
