### PR TITLE
getting-started (rewrote topic)

### PR DESCRIPTION
**Pull request by SKjerland**

### CODE REVIEW

**Comment by sudeepku** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[powerapps-docs/getting-started.md](https://github.com/SKjerland/powerapps-docs-pr/blob/intro/powerapps-docs/getting-started.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powerapps/getting-started?branch=pr-en-us-82) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C11%5C30%5Cf1db111a-32d3-53c6-e514-6b2c2a103d47%5CPullRequest%5C201711302340183277-82%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=Vs5bSM%2Fdj5KbkXxAjy4wYo1bIvdF1%2BdniJWz%2Fb%2F3Bmg%3D&st=2017-11-30T23%3A36%3A27Z&se=2017-12-31T23%3A41%3A27Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by PRMerger9** [comment]
## PRMerger Results
 | Issue | Resolution |
 --- | --- | 
 File Change Percent | This PR contains file(s) with more than 20% file change.

**Comment by sudeepku** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[powerapps-docs/getting-started.md](https://github.com/SKjerland/powerapps-docs-pr/blob/intro/powerapps-docs/getting-started.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powerapps/getting-started?branch=pr-en-us-82) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C12%5C1%5Cf1db111a-32d3-53c6-e514-6b2c2a103d47%5CPullRequest%5C201712010002216483-82%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=nXGrHLlMij%2F2ouFWglGivquJDTiXdxyXuU3y9HUsgWg%3D&st=2017-11-30T23%3A58%3A30Z&se=2018-01-01T00%3A03%3A30Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by PRMerger14** [comment]
## PRMerger Results
 | Issue | Resolution |
 --- | --- | 
 File Change Percent | This PR contains file(s) with more than 20% file change.

**Comment by mgblythe** [comment]
#sign-off b/c Shari is having Git issues

**Pull request merged**
