### PR TITLE
 Port s72 rules update from old repo

### PR DESCRIPTION
**Pull request by mgblythe**

### CODE REVIEW

**Comment by sudeepku** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[powerapps-docs/media/working-with-rules/hover-over-rules_name.png](https://github.com/mgblythe/powerapps-docs-pr/blob/mb-apps-new-work/powerapps-docs/media/working-with-rules/hover-over-rules_name.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powerapps/working-with-rules?branch=pr-en-us-52) |
[powerapps-docs/media/working-with-rules/rename-rule.png](https://github.com/mgblythe/powerapps-docs-pr/blob/mb-apps-new-work/powerapps-docs/media/working-with-rules/rename-rule.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powerapps/working-with-rules?branch=pr-en-us-52) |
[powerapps-docs/media/working-with-rules/rules-filter.png](https://github.com/mgblythe/powerapps-docs-pr/blob/mb-apps-new-work/powerapps-docs/media/working-with-rules/rules-filter.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powerapps/working-with-rules?branch=pr-en-us-52) |
[powerapps-docs/working-with-rules.md](https://github.com/mgblythe/powerapps-docs-pr/blob/mb-apps-new-work/powerapps-docs/working-with-rules.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powerapps/working-with-rules?branch=pr-en-us-52) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C11%5C10%5Cf1db111a-32d3-53c6-e514-6b2c2a103d47%5CPullRequest%5C201711101828504973-52%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=nn04hqQ2EzORcijbbhT07jWIJyvjJcilq1TWoUVq1Rc%3D&st=2017-11-10T18%3A27%3A10Z&se=2017-12-11T18%3A32%3A10Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by sudeepku** [comment]
### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[powerapps-docs/working-with-rules.md](https://github.com/mgblythe/powerapps-docs-pr/blob/mb-apps-new-work/powerapps-docs/working-with-rules.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/powerapps/working-with-rules?branch=pr-en-us-52) | [Details](#user-content-powerapps-docs%2Fworking-with-rules.md)
[powerapps-docs/media/working-with-rules/hover-over-rules_name.png](https://github.com/mgblythe/powerapps-docs-pr/blob/mb-apps-new-work/powerapps-docs/media/working-with-rules/hover-over-rules_name.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powerapps/working-with-rules?branch=pr-en-us-52) |
[powerapps-docs/media/working-with-rules/rename-rule.png](https://github.com/mgblythe/powerapps-docs-pr/blob/mb-apps-new-work/powerapps-docs/media/working-with-rules/rename-rule.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powerapps/working-with-rules?branch=pr-en-us-52) |
[powerapps-docs/media/working-with-rules/rules-filter.png](https://github.com/mgblythe/powerapps-docs-pr/blob/mb-apps-new-work/powerapps-docs/media/working-with-rules/rules-filter.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powerapps/working-with-rules?branch=pr-en-us-52) |

<a name="powerapps-docs%2Fworking-with-rules.md"></a>
### [powerapps-docs/working-with-rules.md](https://github.com/mgblythe/powerapps-docs-pr/blob/mb-apps-new-work/powerapps-docs/working-with-rules.md)
 - **Line 51**: **[Warning]** The content part of NOTE/WARNING/CAUTION/IMPORTANT/NEXT syntax is suggested to start in a new line.

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C11%5C10%5Cf1db111a-32d3-53c6-e514-6b2c2a103d47%5CPullRequest%5C201711101837326758-52%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=CrWlAs8QBah7jZjrtucRb1aflEwuQ5n41wiusvv45x0%3D&st=2017-11-10T18%3A33%3A52Z&se=2017-12-11T18%3A38%3A52Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by sudeepku** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[powerapps-docs/media/working-with-rules/hover-over-rules_name.png](https://github.com/mgblythe/powerapps-docs-pr/blob/mb-apps-new-work/powerapps-docs/media/working-with-rules/hover-over-rules_name.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powerapps/working-with-rules?branch=pr-en-us-52) |
[powerapps-docs/media/working-with-rules/rename-rule.png](https://github.com/mgblythe/powerapps-docs-pr/blob/mb-apps-new-work/powerapps-docs/media/working-with-rules/rename-rule.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powerapps/working-with-rules?branch=pr-en-us-52) |
[powerapps-docs/media/working-with-rules/rules-filter.png](https://github.com/mgblythe/powerapps-docs-pr/blob/mb-apps-new-work/powerapps-docs/media/working-with-rules/rules-filter.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powerapps/working-with-rules?branch=pr-en-us-52) |
[powerapps-docs/working-with-rules.md](https://github.com/mgblythe/powerapps-docs-pr/blob/mb-apps-new-work/powerapps-docs/working-with-rules.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powerapps/working-with-rules?branch=pr-en-us-52) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C11%5C10%5Cf1db111a-32d3-53c6-e514-6b2c2a103d47%5CPullRequest%5C201711101846558859-52%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=z2DSR2DDDaIUV9qG6JSuYe3YQ81aIBPQ181DxPTK%2FVQ%3D&st=2017-11-10T18%3A43%3A07Z&se=2017-12-11T18%3A48%3A07Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by mgblythe** [comment]
#sign-off

**Pull request merged**
