### PR TITLE
Shortened and reworked GL section 3

### PR DESCRIPTION
**Pull request by SKjerland**

### CODE REVIEW

**Comment by sudeepku** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[powerapps-docs/common-issues-and-resolutions.md](https://github.com/SKjerland/powerapps-docs-pr/blob/gl-refresh/powerapps-docs/common-issues-and-resolutions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powerapps/common-issues-and-resolutions?branch=pr-en-us-80) |
[powerapps-docs/guided-learning/learning-add-data-dropdown.md](https://github.com/SKjerland/powerapps-docs-pr/blob/gl-refresh/powerapps-docs/guided-learning/learning-add-data-dropdown.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powerapps/guided-learning/learning-add-data-dropdown?branch=pr-en-us-80) |
[powerapps-docs/guided-learning/learning-forms-add-icons.md](https://github.com/SKjerland/powerapps-docs-pr/blob/gl-refresh/powerapps-docs/guided-learning/learning-forms-add-icons.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powerapps/guided-learning/learning-forms-add-icons?branch=pr-en-us-80) |
[powerapps-docs/guided-learning/learning-forms-edit-mode.md](https://github.com/SKjerland/powerapps-docs-pr/blob/gl-refresh/powerapps-docs/guided-learning/learning-forms-edit-mode.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powerapps/guided-learning/learning-forms-edit-mode?branch=pr-en-us-80) |
[powerapps-docs/guided-learning/learning-forms-hide-icons.md](https://github.com/SKjerland/powerapps-docs-pr/blob/gl-refresh/powerapps-docs/guided-learning/learning-forms-hide-icons.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powerapps/guided-learning/learning-forms-hide-icons?branch=pr-en-us-80) |
[powerapps-docs/guided-learning/learning-prepare-to-create-sharepoint-app.md](https://github.com/SKjerland/powerapps-docs-pr/blob/gl-refresh/powerapps-docs/guided-learning/learning-prepare-to-create-sharepoint-app.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powerapps/guided-learning/learning-prepare-to-create-sharepoint-app?branch=pr-en-us-80) |
[powerapps-docs/guided-learning/learning-understand-basics-forms.md](https://github.com/SKjerland/powerapps-docs-pr/blob/gl-refresh/powerapps-docs/guided-learning/learning-understand-basics-forms.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powerapps/guided-learning/learning-understand-basics-forms?branch=pr-en-us-80) |
[powerapps-docs/guided-learning/learning-understand-basics-formulas.md](https://github.com/SKjerland/powerapps-docs-pr/blob/gl-refresh/powerapps-docs/guided-learning/learning-understand-basics-formulas.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powerapps/guided-learning/learning-understand-basics-formulas?branch=pr-en-us-80) |
[powerapps-docs/sharepoint-form-integration.md](https://github.com/SKjerland/powerapps-docs-pr/blob/gl-refresh/powerapps-docs/sharepoint-form-integration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powerapps/sharepoint-form-integration?branch=pr-en-us-80) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C11%5C29%5Cf1db111a-32d3-53c6-e514-6b2c2a103d47%5CPullRequest%5C201711292035114666-80%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=Por7GitOuFvyoCybHg8Fw4JNBWdRBiLRAb8V5VnwMDA%3D&st=2017-11-29T20%3A31%3A21Z&se=2017-12-30T20%3A36%3A21Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by sudeepku** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[powerapps-docs/common-issues-and-resolutions.md](https://github.com/SKjerland/powerapps-docs-pr/blob/gl-refresh/powerapps-docs/common-issues-and-resolutions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powerapps/common-issues-and-resolutions?branch=pr-en-us-80) |
[powerapps-docs/guided-learning/learning-add-data-dropdown.md](https://github.com/SKjerland/powerapps-docs-pr/blob/gl-refresh/powerapps-docs/guided-learning/learning-add-data-dropdown.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powerapps/guided-learning/learning-add-data-dropdown?branch=pr-en-us-80) |
[powerapps-docs/guided-learning/learning-forms-add-icons.md](https://github.com/SKjerland/powerapps-docs-pr/blob/gl-refresh/powerapps-docs/guided-learning/learning-forms-add-icons.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powerapps/guided-learning/learning-forms-add-icons?branch=pr-en-us-80) |
[powerapps-docs/guided-learning/learning-forms-edit-mode.md](https://github.com/SKjerland/powerapps-docs-pr/blob/gl-refresh/powerapps-docs/guided-learning/learning-forms-edit-mode.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powerapps/guided-learning/learning-forms-edit-mode?branch=pr-en-us-80) |
[powerapps-docs/guided-learning/learning-forms-hide-icons.md](https://github.com/SKjerland/powerapps-docs-pr/blob/gl-refresh/powerapps-docs/guided-learning/learning-forms-hide-icons.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powerapps/guided-learning/learning-forms-hide-icons?branch=pr-en-us-80) |
[powerapps-docs/guided-learning/learning-prepare-to-create-sharepoint-app.md](https://github.com/SKjerland/powerapps-docs-pr/blob/gl-refresh/powerapps-docs/guided-learning/learning-prepare-to-create-sharepoint-app.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powerapps/guided-learning/learning-prepare-to-create-sharepoint-app?branch=pr-en-us-80) |
[powerapps-docs/guided-learning/learning-understand-basics-forms.md](https://github.com/SKjerland/powerapps-docs-pr/blob/gl-refresh/powerapps-docs/guided-learning/learning-understand-basics-forms.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powerapps/guided-learning/learning-understand-basics-forms?branch=pr-en-us-80) |
[powerapps-docs/guided-learning/learning-understand-basics-formulas.md](https://github.com/SKjerland/powerapps-docs-pr/blob/gl-refresh/powerapps-docs/guided-learning/learning-understand-basics-formulas.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powerapps/guided-learning/learning-understand-basics-formulas?branch=pr-en-us-80) |
[powerapps-docs/sharepoint-form-integration.md](https://github.com/SKjerland/powerapps-docs-pr/blob/gl-refresh/powerapps-docs/sharepoint-form-integration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powerapps/sharepoint-form-integration?branch=pr-en-us-80) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C11%5C29%5Cf1db111a-32d3-53c6-e514-6b2c2a103d47%5CPullRequest%5C201711292137517352-80%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=nnBN7UG2HS5O82QIgDII37pDb2NRQ18VqayS3ogsKsI%3D&st=2017-11-29T21%3A34%3A01Z&se=2017-12-30T21%3A39%3A01Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by sudeepku** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[powerapps-docs/common-issues-and-resolutions.md](https://github.com/SKjerland/powerapps-docs-pr/blob/gl-refresh/powerapps-docs/common-issues-and-resolutions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powerapps/common-issues-and-resolutions?branch=pr-en-us-80) |
[powerapps-docs/guided-learning/learning-add-data-dropdown.md](https://github.com/SKjerland/powerapps-docs-pr/blob/gl-refresh/powerapps-docs/guided-learning/learning-add-data-dropdown.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powerapps/guided-learning/learning-add-data-dropdown?branch=pr-en-us-80) |
[powerapps-docs/guided-learning/learning-forms-add-icons.md](https://github.com/SKjerland/powerapps-docs-pr/blob/gl-refresh/powerapps-docs/guided-learning/learning-forms-add-icons.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powerapps/guided-learning/learning-forms-add-icons?branch=pr-en-us-80) |
[powerapps-docs/guided-learning/learning-forms-edit-mode.md](https://github.com/SKjerland/powerapps-docs-pr/blob/gl-refresh/powerapps-docs/guided-learning/learning-forms-edit-mode.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powerapps/guided-learning/learning-forms-edit-mode?branch=pr-en-us-80) |
[powerapps-docs/guided-learning/learning-forms-hide-icons.md](https://github.com/SKjerland/powerapps-docs-pr/blob/gl-refresh/powerapps-docs/guided-learning/learning-forms-hide-icons.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powerapps/guided-learning/learning-forms-hide-icons?branch=pr-en-us-80) |
[powerapps-docs/guided-learning/learning-prepare-to-create-sharepoint-app.md](https://github.com/SKjerland/powerapps-docs-pr/blob/gl-refresh/powerapps-docs/guided-learning/learning-prepare-to-create-sharepoint-app.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powerapps/guided-learning/learning-prepare-to-create-sharepoint-app?branch=pr-en-us-80) |
[powerapps-docs/guided-learning/learning-understand-basics-forms.md](https://github.com/SKjerland/powerapps-docs-pr/blob/gl-refresh/powerapps-docs/guided-learning/learning-understand-basics-forms.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powerapps/guided-learning/learning-understand-basics-forms?branch=pr-en-us-80) |
[powerapps-docs/guided-learning/learning-understand-basics-formulas.md](https://github.com/SKjerland/powerapps-docs-pr/blob/gl-refresh/powerapps-docs/guided-learning/learning-understand-basics-formulas.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powerapps/guided-learning/learning-understand-basics-formulas?branch=pr-en-us-80) |
[powerapps-docs/sharepoint-form-integration.md](https://github.com/SKjerland/powerapps-docs-pr/blob/gl-refresh/powerapps-docs/sharepoint-form-integration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powerapps/sharepoint-form-integration?branch=pr-en-us-80) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C11%5C29%5Cf1db111a-32d3-53c6-e514-6b2c2a103d47%5CPullRequest%5C201711292140214369-80%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=8nRj%2FQ6TAjn2bAAQtR2Qrr%2FPAMiEK3m9ohQXHZonVV8%3D&st=2017-11-29T21%3A36%3A30Z&se=2017-12-30T21%3A41%3A30Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by tysonn** [comment]
Opening/closing to test PRmerger, this PR is not getting the human-review/auto-merge labels.

**Comment by sudeepku** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[powerapps-docs/common-issues-and-resolutions.md](https://github.com/SKjerland/powerapps-docs-pr/blob/gl-refresh/powerapps-docs/common-issues-and-resolutions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powerapps/common-issues-and-resolutions?branch=pr-en-us-80) |
[powerapps-docs/guided-learning/learning-add-data-dropdown.md](https://github.com/SKjerland/powerapps-docs-pr/blob/gl-refresh/powerapps-docs/guided-learning/learning-add-data-dropdown.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powerapps/guided-learning/learning-add-data-dropdown?branch=pr-en-us-80) |
[powerapps-docs/guided-learning/learning-forms-add-icons.md](https://github.com/SKjerland/powerapps-docs-pr/blob/gl-refresh/powerapps-docs/guided-learning/learning-forms-add-icons.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powerapps/guided-learning/learning-forms-add-icons?branch=pr-en-us-80) |
[powerapps-docs/guided-learning/learning-forms-edit-mode.md](https://github.com/SKjerland/powerapps-docs-pr/blob/gl-refresh/powerapps-docs/guided-learning/learning-forms-edit-mode.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powerapps/guided-learning/learning-forms-edit-mode?branch=pr-en-us-80) |
[powerapps-docs/guided-learning/learning-forms-hide-icons.md](https://github.com/SKjerland/powerapps-docs-pr/blob/gl-refresh/powerapps-docs/guided-learning/learning-forms-hide-icons.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powerapps/guided-learning/learning-forms-hide-icons?branch=pr-en-us-80) |
[powerapps-docs/guided-learning/learning-prepare-to-create-sharepoint-app.md](https://github.com/SKjerland/powerapps-docs-pr/blob/gl-refresh/powerapps-docs/guided-learning/learning-prepare-to-create-sharepoint-app.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powerapps/guided-learning/learning-prepare-to-create-sharepoint-app?branch=pr-en-us-80) |
[powerapps-docs/guided-learning/learning-understand-basics-forms.md](https://github.com/SKjerland/powerapps-docs-pr/blob/gl-refresh/powerapps-docs/guided-learning/learning-understand-basics-forms.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powerapps/guided-learning/learning-understand-basics-forms?branch=pr-en-us-80) |
[powerapps-docs/guided-learning/learning-understand-basics-formulas.md](https://github.com/SKjerland/powerapps-docs-pr/blob/gl-refresh/powerapps-docs/guided-learning/learning-understand-basics-formulas.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powerapps/guided-learning/learning-understand-basics-formulas?branch=pr-en-us-80) |
[powerapps-docs/sharepoint-form-integration.md](https://github.com/SKjerland/powerapps-docs-pr/blob/gl-refresh/powerapps-docs/sharepoint-form-integration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powerapps/sharepoint-form-integration?branch=pr-en-us-80) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C11%5C29%5Cf1db111a-32d3-53c6-e514-6b2c2a103d47%5CPullRequest%5C201711292147165812-80%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=yGNJJmiSGdxKaOIQD6AmOYqXYTUQla6kzjn7ECIWj6M%3D&st=2017-11-29T21%3A43%3A33Z&se=2017-12-30T21%3A48%3A33Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by tysonn** [comment]
Bug filed for lack of merge labels: https://mseng.visualstudio.com/DefaultCollection/CSI/docs Authoring Experiences/_workItems?id=1136131

**Comment by mgblythe** [comment]
Merging before I do a reset on the repo

**Pull request merged**
