### PR TITLE
Updated Common Issues and What's New for S73 release.

### PR DESCRIPTION
**Pull request by SKjerland**

### CODE REVIEW

**Comment by sudeepku** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[powerapps-docs/common-issues-and-resolutions.md](https://github.com/SKjerland/powerapps-docs-pr/blob/s73/powerapps-docs/common-issues-and-resolutions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powerapps/common-issues-and-resolutions?branch=pr-en-us-86) |
[powerapps-docs/release-notes.md](https://github.com/SKjerland/powerapps-docs-pr/blob/s73/powerapps-docs/release-notes.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powerapps/release-notes?branch=pr-en-us-86) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C12%5C5%5Cf1db111a-32d3-53c6-e514-6b2c2a103d47%5CPullRequest%5C201712050100505107-86%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=2%2FqZvFPXgYMdXDbNTAU7UhQ%2BYIVoB2u0Fu9%2BgK0V5T0%3D&st=2017-12-05T00%3A57%3A30Z&se=2018-01-05T01%3A02%3A30Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by PRMerger17** [comment]
## PRMerger Results
 | Issue | Resolution |
 --- | --- | 
 File Change Percent | This PR contains file(s) with more than 20% file change.

**Comment by sudeepku** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[powerapps-docs/common-issues-and-resolutions.md](https://github.com/SKjerland/powerapps-docs-pr/blob/s73/powerapps-docs/common-issues-and-resolutions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powerapps/common-issues-and-resolutions?branch=pr-en-us-86) |
[powerapps-docs/media/getting-started/sample-apps.png](https://github.com/SKjerland/powerapps-docs-pr/blob/s73/powerapps-docs/media/getting-started/sample-apps.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powerapps/getting-started?branch=pr-en-us-86) |
[powerapps-docs/release-notes.md](https://github.com/SKjerland/powerapps-docs-pr/blob/s73/powerapps-docs/release-notes.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powerapps/release-notes?branch=pr-en-us-86) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C12%5C6%5Cf1db111a-32d3-53c6-e514-6b2c2a103d47%5CPullRequest%5C201712060209455427-86%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=4kaspiZf6I%2BF2XzRAuHhqI5iL1NT5J%2F3FROQ1AJrGHc%3D&st=2017-12-06T02%3A06%3A24Z&se=2018-01-06T02%3A11%3A24Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by SKjerland** [comment]
#sign-off

**Comment by Lisaco88** [comment]
In review.

**Comment by Lisaco88** [comment]
No issues; merging now.

**Pull request merged**
