### PR TITLE
Fixed formatting errors in multiple files

### PR DESCRIPTION
**Pull request by SKjerland**

### CODE REVIEW

**Comment by sudeepku** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[powerapps-docs/add-gallery.md](https://github.com/SKjerland/powerapps-docs-pr/blob/cleanup/powerapps-docs/add-gallery.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powerapps/add-gallery?branch=pr-en-us-36) |
[powerapps-docs/app-source.md](https://github.com/SKjerland/powerapps-docs-pr/blob/cleanup/powerapps-docs/app-source.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powerapps/app-source?branch=pr-en-us-36) |
[powerapps-docs/dev-community-plan.md](https://github.com/SKjerland/powerapps-docs-pr/blob/cleanup/powerapps-docs/dev-community-plan.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powerapps/dev-community-plan?branch=pr-en-us-36) |
[powerapps-docs/media/add-gallery/final-gallery.png](https://github.com/SKjerland/powerapps-docs-pr/blob/cleanup/powerapps-docs/media/add-gallery/final-gallery.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powerapps/add-gallery?branch=pr-en-us-36) |
[powerapps-docs/signup-for-powerapps-admin.md](https://github.com/SKjerland/powerapps-docs-pr/blob/cleanup/powerapps-docs/signup-for-powerapps-admin.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powerapps/signup-for-powerapps-admin?branch=pr-en-us-36) |
[powerapps-docs/signup-for-powerapps.md](https://github.com/SKjerland/powerapps-docs-pr/blob/cleanup/powerapps-docs/signup-for-powerapps.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powerapps/signup-for-powerapps?branch=pr-en-us-36) |
[powerapps-docs/working-with-environments.md](https://github.com/SKjerland/powerapps-docs-pr/blob/cleanup/powerapps-docs/working-with-environments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powerapps/working-with-environments?branch=pr-en-us-36) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C11%5C8%5Cf1db111a-32d3-53c6-e514-6b2c2a103d47%5CPullRequest%5C201711082129181120-36%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=Q%2FcjZV3izbSYKHi6k38c6ibyIqpaU%2BJrFEDlCH1N6ow%3D&st=2017-11-08T21%3A25%3A32Z&se=2017-12-09T21%3A30%3A32Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by sudeepku** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[powerapps-docs/add-gallery.md](https://github.com/SKjerland/powerapps-docs-pr/blob/cleanup/powerapps-docs/add-gallery.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powerapps/add-gallery?branch=pr-en-us-36) |
[powerapps-docs/app-source.md](https://github.com/SKjerland/powerapps-docs-pr/blob/cleanup/powerapps-docs/app-source.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powerapps/app-source?branch=pr-en-us-36) |
[powerapps-docs/delegation-list.md](https://github.com/SKjerland/powerapps-docs-pr/blob/cleanup/powerapps-docs/delegation-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powerapps/delegation-list?branch=pr-en-us-36) |
[powerapps-docs/dev-community-plan.md](https://github.com/SKjerland/powerapps-docs-pr/blob/cleanup/powerapps-docs/dev-community-plan.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powerapps/dev-community-plan?branch=pr-en-us-36) |
[powerapps-docs/media/add-gallery/final-gallery.png](https://github.com/SKjerland/powerapps-docs-pr/blob/cleanup/powerapps-docs/media/add-gallery/final-gallery.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powerapps/add-gallery?branch=pr-en-us-36) |
[powerapps-docs/signup-for-powerapps-admin.md](https://github.com/SKjerland/powerapps-docs-pr/blob/cleanup/powerapps-docs/signup-for-powerapps-admin.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powerapps/signup-for-powerapps-admin?branch=pr-en-us-36) |
[powerapps-docs/signup-for-powerapps.md](https://github.com/SKjerland/powerapps-docs-pr/blob/cleanup/powerapps-docs/signup-for-powerapps.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powerapps/signup-for-powerapps?branch=pr-en-us-36) |
[powerapps-docs/working-with-environments.md](https://github.com/SKjerland/powerapps-docs-pr/blob/cleanup/powerapps-docs/working-with-environments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powerapps/working-with-environments?branch=pr-en-us-36) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C11%5C8%5Cf1db111a-32d3-53c6-e514-6b2c2a103d47%5CPullRequest%5C201711082227532759-36%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=jRQ3%2Fgygff2EZmv2AEcreOjWyVTOpQcvx%2FJd2s6LlUE%3D&st=2017-11-08T22%3A24%3A59Z&se=2017-12-09T22%3A29%3A59Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by sudeepku** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[powerapps-docs/add-gallery.md](https://github.com/SKjerland/powerapps-docs-pr/blob/cleanup/powerapps-docs/add-gallery.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powerapps/add-gallery?branch=pr-en-us-36) |
[powerapps-docs/app-source.md](https://github.com/SKjerland/powerapps-docs-pr/blob/cleanup/powerapps-docs/app-source.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powerapps/app-source?branch=pr-en-us-36) |
[powerapps-docs/delegation-list.md](https://github.com/SKjerland/powerapps-docs-pr/blob/cleanup/powerapps-docs/delegation-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powerapps/delegation-list?branch=pr-en-us-36) |
[powerapps-docs/dev-community-plan.md](https://github.com/SKjerland/powerapps-docs-pr/blob/cleanup/powerapps-docs/dev-community-plan.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powerapps/dev-community-plan?branch=pr-en-us-36) |
[powerapps-docs/media/add-gallery/final-gallery.png](https://github.com/SKjerland/powerapps-docs-pr/blob/cleanup/powerapps-docs/media/add-gallery/final-gallery.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powerapps/add-gallery?branch=pr-en-us-36) |
[powerapps-docs/signup-for-powerapps-admin.md](https://github.com/SKjerland/powerapps-docs-pr/blob/cleanup/powerapps-docs/signup-for-powerapps-admin.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powerapps/signup-for-powerapps-admin?branch=pr-en-us-36) |
[powerapps-docs/signup-for-powerapps.md](https://github.com/SKjerland/powerapps-docs-pr/blob/cleanup/powerapps-docs/signup-for-powerapps.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powerapps/signup-for-powerapps?branch=pr-en-us-36) |
[powerapps-docs/working-with-environments.md](https://github.com/SKjerland/powerapps-docs-pr/blob/cleanup/powerapps-docs/working-with-environments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powerapps/working-with-environments?branch=pr-en-us-36) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C11%5C8%5Cf1db111a-32d3-53c6-e514-6b2c2a103d47%5CPullRequest%5C201711082242101134-36%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=m3ruPm%2BCOVhgYgL%2FrEAhjPwG4oEe8tVYk%2BNbgv30d4U%3D&st=2017-11-08T22%3A39%3A07Z&se=2017-12-09T22%3A44%3A07Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by SKjerland** [comment]
#sign-off

**Comment by sudeepku** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[powerapps-docs/add-gallery.md](https://github.com/SKjerland/powerapps-docs-pr/blob/cleanup/powerapps-docs/add-gallery.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powerapps/add-gallery?branch=pr-en-us-36) |
[powerapps-docs/app-source.md](https://github.com/SKjerland/powerapps-docs-pr/blob/cleanup/powerapps-docs/app-source.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powerapps/app-source?branch=pr-en-us-36) |
[powerapps-docs/connect-to-sharepoint.md](https://github.com/SKjerland/powerapps-docs-pr/blob/cleanup/powerapps-docs/connect-to-sharepoint.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powerapps/connect-to-sharepoint?branch=pr-en-us-36) |
[powerapps-docs/customize-card.md](https://github.com/SKjerland/powerapps-docs-pr/blob/cleanup/powerapps-docs/customize-card.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powerapps/customize-card?branch=pr-en-us-36) |
[powerapps-docs/customize-forms-sharepoint.md](https://github.com/SKjerland/powerapps-docs-pr/blob/cleanup/powerapps-docs/customize-forms-sharepoint.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powerapps/customize-forms-sharepoint?branch=pr-en-us-36) |
[powerapps-docs/delegation-list.md](https://github.com/SKjerland/powerapps-docs-pr/blob/cleanup/powerapps-docs/delegation-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powerapps/delegation-list?branch=pr-en-us-36) |
[powerapps-docs/dev-community-plan.md](https://github.com/SKjerland/powerapps-docs-pr/blob/cleanup/powerapps-docs/dev-community-plan.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powerapps/dev-community-plan?branch=pr-en-us-36) |
[powerapps-docs/get-started-test-drive.md](https://github.com/SKjerland/powerapps-docs-pr/blob/cleanup/powerapps-docs/get-started-test-drive.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powerapps/get-started-test-drive?branch=pr-en-us-36) |
[powerapps-docs/media/add-gallery/final-gallery.png](https://github.com/SKjerland/powerapps-docs-pr/blob/cleanup/powerapps-docs/media/add-gallery/final-gallery.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powerapps/add-gallery?branch=pr-en-us-36) |
[powerapps-docs/open-and-run-a-sample-app.md](https://github.com/SKjerland/powerapps-docs-pr/blob/cleanup/powerapps-docs/open-and-run-a-sample-app.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powerapps/open-and-run-a-sample-app?branch=pr-en-us-36) |
[powerapps-docs/run-app-client.md](https://github.com/SKjerland/powerapps-docs-pr/blob/cleanup/powerapps-docs/run-app-client.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powerapps/run-app-client?branch=pr-en-us-36) |
[powerapps-docs/sharepoint-lookup-fields.md](https://github.com/SKjerland/powerapps-docs-pr/blob/cleanup/powerapps-docs/sharepoint-lookup-fields.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powerapps/sharepoint-lookup-fields?branch=pr-en-us-36) |
[powerapps-docs/signup-for-powerapps-admin.md](https://github.com/SKjerland/powerapps-docs-pr/blob/cleanup/powerapps-docs/signup-for-powerapps-admin.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powerapps/signup-for-powerapps-admin?branch=pr-en-us-36) |
[powerapps-docs/signup-for-powerapps.md](https://github.com/SKjerland/powerapps-docs-pr/blob/cleanup/powerapps-docs/signup-for-powerapps.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powerapps/signup-for-powerapps?branch=pr-en-us-36) |
[powerapps-docs/working-with-environments.md](https://github.com/SKjerland/powerapps-docs-pr/blob/cleanup/powerapps-docs/working-with-environments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powerapps/working-with-environments?branch=pr-en-us-36) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C11%5C9%5Cf1db111a-32d3-53c6-e514-6b2c2a103d47%5CPullRequest%5C201711090033380719-36%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=a4ra645eO%2BAzDhjueHg2DZwamvCk7kTe4gOLuubrAso%3D&st=2017-11-09T00%3A32%3A03Z&se=2017-12-10T00%3A37%3A03Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by sudeepku** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[powerapps-docs/add-gallery.md](https://github.com/SKjerland/powerapps-docs-pr/blob/cleanup/powerapps-docs/add-gallery.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powerapps/add-gallery?branch=pr-en-us-36) |
[powerapps-docs/app-source.md](https://github.com/SKjerland/powerapps-docs-pr/blob/cleanup/powerapps-docs/app-source.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powerapps/app-source?branch=pr-en-us-36) |
[powerapps-docs/connect-to-sharepoint.md](https://github.com/SKjerland/powerapps-docs-pr/blob/cleanup/powerapps-docs/connect-to-sharepoint.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powerapps/connect-to-sharepoint?branch=pr-en-us-36) |
[powerapps-docs/customize-card.md](https://github.com/SKjerland/powerapps-docs-pr/blob/cleanup/powerapps-docs/customize-card.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powerapps/customize-card?branch=pr-en-us-36) |
[powerapps-docs/customize-forms-sharepoint.md](https://github.com/SKjerland/powerapps-docs-pr/blob/cleanup/powerapps-docs/customize-forms-sharepoint.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powerapps/customize-forms-sharepoint?branch=pr-en-us-36) |
[powerapps-docs/data-platform-create-app.md](https://github.com/SKjerland/powerapps-docs-pr/blob/cleanup/powerapps-docs/data-platform-create-app.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powerapps/data-platform-create-app?branch=pr-en-us-36) |
[powerapps-docs/delegation-list.md](https://github.com/SKjerland/powerapps-docs-pr/blob/cleanup/powerapps-docs/delegation-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powerapps/delegation-list?branch=pr-en-us-36) |
[powerapps-docs/dev-community-plan.md](https://github.com/SKjerland/powerapps-docs-pr/blob/cleanup/powerapps-docs/dev-community-plan.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powerapps/dev-community-plan?branch=pr-en-us-36) |
[powerapps-docs/get-started-test-drive.md](https://github.com/SKjerland/powerapps-docs-pr/blob/cleanup/powerapps-docs/get-started-test-drive.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powerapps/get-started-test-drive?branch=pr-en-us-36) |
[powerapps-docs/media/add-gallery/final-gallery.png](https://github.com/SKjerland/powerapps-docs-pr/blob/cleanup/powerapps-docs/media/add-gallery/final-gallery.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powerapps/add-gallery?branch=pr-en-us-36) |
[powerapps-docs/open-and-run-a-sample-app.md](https://github.com/SKjerland/powerapps-docs-pr/blob/cleanup/powerapps-docs/open-and-run-a-sample-app.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powerapps/open-and-run-a-sample-app?branch=pr-en-us-36) |
[powerapps-docs/run-app-client.md](https://github.com/SKjerland/powerapps-docs-pr/blob/cleanup/powerapps-docs/run-app-client.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powerapps/run-app-client?branch=pr-en-us-36) |
[powerapps-docs/sharepoint-lookup-fields.md](https://github.com/SKjerland/powerapps-docs-pr/blob/cleanup/powerapps-docs/sharepoint-lookup-fields.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powerapps/sharepoint-lookup-fields?branch=pr-en-us-36) |
[powerapps-docs/signup-for-powerapps-admin.md](https://github.com/SKjerland/powerapps-docs-pr/blob/cleanup/powerapps-docs/signup-for-powerapps-admin.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powerapps/signup-for-powerapps-admin?branch=pr-en-us-36) |
[powerapps-docs/signup-for-powerapps.md](https://github.com/SKjerland/powerapps-docs-pr/blob/cleanup/powerapps-docs/signup-for-powerapps.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powerapps/signup-for-powerapps?branch=pr-en-us-36) |
[powerapps-docs/working-with-environments.md](https://github.com/SKjerland/powerapps-docs-pr/blob/cleanup/powerapps-docs/working-with-environments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powerapps/working-with-environments?branch=pr-en-us-36) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C11%5C9%5Cf1db111a-32d3-53c6-e514-6b2c2a103d47%5CPullRequest%5C201711090048260733-36%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=rtwQMyzEtzhHsDdTr%2FCgi362fi7zQwKUBN%2BiDlaCew4%3D&st=2017-11-09T00%3A46%3A08Z&se=2017-12-10T00%3A51%3A08Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by SKjerland** [comment]
#sign-off

**Pull request merged**
