### PR TITLE
SharePoint freshness

### PR DESCRIPTION
**Pull request by mgblythe**

### CODE REVIEW

**Comment by mgblythe** [comment]
#sign-off

**Comment by PRMerger7** [comment]
Only the author, @mblythe, can sign off on this pull request.

**Comment by PRMerger17** [comment]
@mgblythe : Thanks for your contribution to the Azure documentation! The author, @mblythe, has been notified to review your proposed change.

**Comment by PRMerger12** [comment]
@mgblythe : Thanks for your contribution to the Azure documentation! The author, @mblythe, has been notified to review your proposed change.

**Pull request merged**
