### PR TITLE
fixed formatting in section 5

### PR DESCRIPTION
**Pull request by SKjerland**

### CODE REVIEW

**Comment by sudeepku** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[powerapps-docs/add-configure-controls.md](https://github.com/SKjerland/powerapps-docs-pr/blob/section5/powerapps-docs/add-configure-controls.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powerapps/add-configure-controls?branch=pr-en-us-41) |
[powerapps-docs/add-data-connection.md](https://github.com/SKjerland/powerapps-docs-pr/blob/section5/powerapps-docs/add-data-connection.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powerapps/add-data-connection?branch=pr-en-us-41) |
[powerapps-docs/add-form.md](https://github.com/SKjerland/powerapps-docs-pr/blob/section5/powerapps-docs/add-form.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powerapps/add-form?branch=pr-en-us-41) |
[powerapps-docs/add-gallery.md](https://github.com/SKjerland/powerapps-docs-pr/blob/section5/powerapps-docs/add-gallery.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powerapps/add-gallery?branch=pr-en-us-41) |
[powerapps-docs/add-images-pictures-audio-video.md](https://github.com/SKjerland/powerapps-docs-pr/blob/section5/powerapps-docs/add-images-pictures-audio-video.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powerapps/add-images-pictures-audio-video?branch=pr-en-us-41) |
[powerapps-docs/add-list-box-drop-down-list-radio-button.md](https://github.com/SKjerland/powerapps-docs-pr/blob/section5/powerapps-docs/add-list-box-drop-down-list-radio-button.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powerapps/add-list-box-drop-down-list-radio-button?branch=pr-en-us-41) |
[powerapps-docs/add-screen-context-variables.md](https://github.com/SKjerland/powerapps-docs-pr/blob/section5/powerapps-docs/add-screen-context-variables.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powerapps/add-screen-context-variables?branch=pr-en-us-41) |
[powerapps-docs/gallery-dynamic-sizing.md](https://github.com/SKjerland/powerapps-docs-pr/blob/section5/powerapps-docs/gallery-dynamic-sizing.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powerapps/gallery-dynamic-sizing?branch=pr-en-us-41) |
[powerapps-docs/global-apps.md](https://github.com/SKjerland/powerapps-docs-pr/blob/section5/powerapps-docs/global-apps.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powerapps/global-apps?branch=pr-en-us-41) |
[powerapps-docs/scan-barcode.md](https://github.com/SKjerland/powerapps-docs-pr/blob/section5/powerapps-docs/scan-barcode.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powerapps/scan-barcode?branch=pr-en-us-41) |
[powerapps-docs/use-line-pie-bar-chart.md](https://github.com/SKjerland/powerapps-docs-pr/blob/section5/powerapps-docs/use-line-pie-bar-chart.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powerapps/use-line-pie-bar-chart?branch=pr-en-us-41) |
[powerapps-docs/using-logic-flows.md](https://github.com/SKjerland/powerapps-docs-pr/blob/section5/powerapps-docs/using-logic-flows.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powerapps/using-logic-flows?branch=pr-en-us-41) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C11%5C9%5Cf1db111a-32d3-53c6-e514-6b2c2a103d47%5CPullRequest%5C201711090517125228-41%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=MJ4w76a2ElbT1g8IQgeWvpPTuF9Q2kDOSzfFa3LR5fo%3D&st=2017-11-09T05%3A13%3A45Z&se=2017-12-10T05%3A18%3A45Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by sudeepku** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[powerapps-docs/add-configure-controls.md](https://github.com/SKjerland/powerapps-docs-pr/blob/section5/powerapps-docs/add-configure-controls.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powerapps/add-configure-controls?branch=pr-en-us-41) |
[powerapps-docs/add-data-connection.md](https://github.com/SKjerland/powerapps-docs-pr/blob/section5/powerapps-docs/add-data-connection.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powerapps/add-data-connection?branch=pr-en-us-41) |
[powerapps-docs/add-form.md](https://github.com/SKjerland/powerapps-docs-pr/blob/section5/powerapps-docs/add-form.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powerapps/add-form?branch=pr-en-us-41) |
[powerapps-docs/add-gallery.md](https://github.com/SKjerland/powerapps-docs-pr/blob/section5/powerapps-docs/add-gallery.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powerapps/add-gallery?branch=pr-en-us-41) |
[powerapps-docs/add-images-pictures-audio-video.md](https://github.com/SKjerland/powerapps-docs-pr/blob/section5/powerapps-docs/add-images-pictures-audio-video.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powerapps/add-images-pictures-audio-video?branch=pr-en-us-41) |
[powerapps-docs/add-list-box-drop-down-list-radio-button.md](https://github.com/SKjerland/powerapps-docs-pr/blob/section5/powerapps-docs/add-list-box-drop-down-list-radio-button.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powerapps/add-list-box-drop-down-list-radio-button?branch=pr-en-us-41) |
[powerapps-docs/add-screen-context-variables.md](https://github.com/SKjerland/powerapps-docs-pr/blob/section5/powerapps-docs/add-screen-context-variables.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powerapps/add-screen-context-variables?branch=pr-en-us-41) |
[powerapps-docs/gallery-dynamic-sizing.md](https://github.com/SKjerland/powerapps-docs-pr/blob/section5/powerapps-docs/gallery-dynamic-sizing.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powerapps/gallery-dynamic-sizing?branch=pr-en-us-41) |
[powerapps-docs/global-apps.md](https://github.com/SKjerland/powerapps-docs-pr/blob/section5/powerapps-docs/global-apps.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powerapps/global-apps?branch=pr-en-us-41) |
[powerapps-docs/scan-barcode.md](https://github.com/SKjerland/powerapps-docs-pr/blob/section5/powerapps-docs/scan-barcode.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powerapps/scan-barcode?branch=pr-en-us-41) |
[powerapps-docs/use-line-pie-bar-chart.md](https://github.com/SKjerland/powerapps-docs-pr/blob/section5/powerapps-docs/use-line-pie-bar-chart.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powerapps/use-line-pie-bar-chart?branch=pr-en-us-41) |
[powerapps-docs/using-logic-flows.md](https://github.com/SKjerland/powerapps-docs-pr/blob/section5/powerapps-docs/using-logic-flows.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powerapps/using-logic-flows?branch=pr-en-us-41) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C11%5C9%5Cf1db111a-32d3-53c6-e514-6b2c2a103d47%5CPullRequest%5C201711090553227768-41%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=lsSczmrrU19zSr%2Bwb%2FoAcGwedKEbjdxLsSk%2FHgbqYRU%3D&st=2017-11-09T05%3A49%3A55Z&se=2017-12-10T05%3A54%3A55Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by sudeepku** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[powerapps-docs/add-configure-controls.md](https://github.com/SKjerland/powerapps-docs-pr/blob/section5/powerapps-docs/add-configure-controls.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powerapps/add-configure-controls?branch=pr-en-us-41) |
[powerapps-docs/add-data-connection.md](https://github.com/SKjerland/powerapps-docs-pr/blob/section5/powerapps-docs/add-data-connection.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powerapps/add-data-connection?branch=pr-en-us-41) |
[powerapps-docs/add-form.md](https://github.com/SKjerland/powerapps-docs-pr/blob/section5/powerapps-docs/add-form.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powerapps/add-form?branch=pr-en-us-41) |
[powerapps-docs/add-gallery.md](https://github.com/SKjerland/powerapps-docs-pr/blob/section5/powerapps-docs/add-gallery.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powerapps/add-gallery?branch=pr-en-us-41) |
[powerapps-docs/add-images-pictures-audio-video.md](https://github.com/SKjerland/powerapps-docs-pr/blob/section5/powerapps-docs/add-images-pictures-audio-video.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powerapps/add-images-pictures-audio-video?branch=pr-en-us-41) |
[powerapps-docs/add-list-box-drop-down-list-radio-button.md](https://github.com/SKjerland/powerapps-docs-pr/blob/section5/powerapps-docs/add-list-box-drop-down-list-radio-button.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powerapps/add-list-box-drop-down-list-radio-button?branch=pr-en-us-41) |
[powerapps-docs/add-screen-context-variables.md](https://github.com/SKjerland/powerapps-docs-pr/blob/section5/powerapps-docs/add-screen-context-variables.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powerapps/add-screen-context-variables?branch=pr-en-us-41) |
[powerapps-docs/gallery-dynamic-sizing.md](https://github.com/SKjerland/powerapps-docs-pr/blob/section5/powerapps-docs/gallery-dynamic-sizing.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powerapps/gallery-dynamic-sizing?branch=pr-en-us-41) |
[powerapps-docs/global-apps.md](https://github.com/SKjerland/powerapps-docs-pr/blob/section5/powerapps-docs/global-apps.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powerapps/global-apps?branch=pr-en-us-41) |
[powerapps-docs/scan-barcode.md](https://github.com/SKjerland/powerapps-docs-pr/blob/section5/powerapps-docs/scan-barcode.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powerapps/scan-barcode?branch=pr-en-us-41) |
[powerapps-docs/use-line-pie-bar-chart.md](https://github.com/SKjerland/powerapps-docs-pr/blob/section5/powerapps-docs/use-line-pie-bar-chart.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powerapps/use-line-pie-bar-chart?branch=pr-en-us-41) |
[powerapps-docs/using-logic-flows.md](https://github.com/SKjerland/powerapps-docs-pr/blob/section5/powerapps-docs/using-logic-flows.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powerapps/using-logic-flows?branch=pr-en-us-41) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C11%5C9%5Cf1db111a-32d3-53c6-e514-6b2c2a103d47%5CPullRequest%5C201711090616095894-41%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=91iUh0DwrQiSdXr0cNHTE3MmKjChsBZ4EIicdc%2FUlC4%3D&st=2017-11-09T06%3A12%3A35Z&se=2017-12-10T06%3A17%3A35Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by SKjerland** [comment]
#sign-off

**Pull request merged**
