### PR TITLE
Update working-with-rules

### PR DESCRIPTION
**Pull request by matthewbolanos**
Properties are now included in condition templates, so I removed the note about it coming in a future release. I also updated the image now that we only show conditions that make sense for a particular control.

### CODE REVIEW

**Comment by sudeepku** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[powerapps-docs/media/working-with-rules/rule-conditions.png](https://github.com/matthewbolanos/powerapps-docs-pr/blob/master/powerapps-docs/media/working-with-rules/rule-conditions.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powerapps/working-with-rules?branch=pr-en-us-81) |
[powerapps-docs/working-with-rules.md](https://github.com/matthewbolanos/powerapps-docs-pr/blob/master/powerapps-docs/working-with-rules.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powerapps/working-with-rules?branch=pr-en-us-81) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C11%5C30%5Cf1db111a-32d3-53c6-e514-6b2c2a103d47%5CPullRequest%5C201711301850091914-81%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=XDMrI7hEI82DA0Y%2BypKFYNJzrJ1I7SQoIZinlVR8xyU%3D&st=2017-11-30T18%3A46%3A33Z&se=2017-12-31T18%3A51%3A33Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by PRMerger13** [comment]
## PRMerger Results
 | Issue | Resolution |
 --- | --- | 
 Image File | This PR contains an image file(s).

**Comment by mgblythe** [comment]
@matthewbolanos -- if you're happy with the results on staging and this can go live now, add a #sign-off comment in GitHub. Thanks!

**Comment by AFTOwen** [comment]
#hold-off

**Comment by sudeepku** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[powerapps-docs/media/working-with-rules/new-rule.png](https://github.com/matthewbolanos/powerapps-docs-pr/blob/master/powerapps-docs/media/working-with-rules/new-rule.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powerapps/working-with-rules?branch=pr-en-us-81) |
[powerapps-docs/media/working-with-rules/rule-conditions.png](https://github.com/matthewbolanos/powerapps-docs-pr/blob/master/powerapps-docs/media/working-with-rules/rule-conditions.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powerapps/working-with-rules?branch=pr-en-us-81) |
[powerapps-docs/working-with-rules.md](https://github.com/matthewbolanos/powerapps-docs-pr/blob/master/powerapps-docs/working-with-rules.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powerapps/working-with-rules?branch=pr-en-us-81) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C12%5C5%5Cf1db111a-32d3-53c6-e514-6b2c2a103d47%5CPullRequest%5C201712051710279535-81%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=GJtjZFS8EioQV84xSNFrlx%2FVNq0IhWLaFCPAnY7X45Q%3D&st=2017-12-05T17%3A07%3A14Z&se=2018-01-05T17%3A12%3A14Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by PRMerger8** [comment]
## PRMerger Results
 | Issue | Resolution |
 --- | --- | 
 Image File | This PR contains an image file(s).

**Comment by matthewbolanos** [comment]
#sign-off

**Comment by Lisaco88** [comment]
In review.

**Comment by Lisaco88** [comment]
No issues; merging now.

**Pull request merged**
