### PR TITLE
release-notes (added note about PowerApps custom visual in Power BI)

### PR DESCRIPTION
**Pull request by SKjerland**
Content update not tied to a release

### CODE REVIEW

**Comment by SKjerland** [comment]
#sign-off

**Comment by Ja-Dunn** [comment]
In review.

**Comment by Ja-Dunn** [comment]
@SKjerland - Hi Shari, because this article is pre-existing (you are only updating now), I am merging. Please do check with Tyson Nevil though about whether release notes are appropriate for PowerApps. Here's the relevant guidance:
--Release notes: Release notes may be published only for products that are delivered as software or as an SDK. For example, in Azure, Storage Explorer, StorSimple, and SDKs are delivered as static, versioned products. Products that are delivered to customers as services are not versioned and therefore should not have release notes - the information you would have traditionally delivered upon release of new functionality should just be embedded in the relevant technical content or included in the service updates channel for the service.
Thanks!

**Comment by SKjerland** [comment]
Thanks, James. The file is named release-notes.md, but the topic is called **What's New in PowerApps**. They're not really release notes in the traditional sense. We're good to go, but thanks for checking with me about this.

**Pull request merged**
