### PR TITLE
Updated What's New for Train 18013

### PR DESCRIPTION
**Pull request by SKjerland**
Part of Train 18013

### CODE REVIEW

**Comment by PRMerger17** [comment]
@SKjerland : Thanks for your contribution to the Azure documentation! The author, @sharik, has been notified to review your proposed change.

**Comment by PRMerger18** [comment]
@SKjerland : Thanks for your contribution to the Azure documentation! The author, @sharik, has been notified to review your proposed change.

**Comment by PRMerger16** [comment]
@SKjerland : Thanks for your contribution to the Azure documentation! The author, @sharik, has been notified to review your proposed change.

**Comment by PRMerger6** [comment]
@SKjerland : Thanks for your contribution to the Azure documentation! The author, @sharik, has been notified to review your proposed change.

**Comment by PRMerger19** [comment]
@SKjerland : Thanks for your contribution to the Azure documentation! The author, @sharik, has been notified to review your proposed change.

**Comment by PRMerger6** [comment]
@SKjerland : Thanks for your contribution to the Azure documentation! The author, @sharik, has been notified to review your proposed change.

**Comment by SKjerland** [comment]
#sign-off

**Comment by PRMerger17** [comment]
Only the author, @sharik, can sign off on this pull request.

**Comment by mgblythe** [comment]
@SKjerland -- ignore the bogus warnings. I will handle this.

**Comment by SKjerland** [comment]
Thanks!

Sent from my iPhone

On Jan 17, 2018, at 2:31 PM, Michael Blythe <notifications@github.com<mailto:notifications@github.com>> wrote:


@SKjerland<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fskjerland&data=02%7C01%7CShari.Kjerland%40microsoft.com%7C1fab40938abf4f53514e08d55dfa0886%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C636518250860415313&sdata=4gE8MGF3P87QKS%2FBkEd1%2B%2FYKuu83UP6aGsSNZbp3drw%3D&reserved=0> -- ignore the bogus warnings. I will handle this.

**Pull request merged**
