### PR TITLE
fixing the alerts and videos in refreshed files

### PR DESCRIPTION
**Pull request by v-thepet**

### CODE REVIEW

**Comment by sudeepku** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[powerapps-docs/connections/connection-office365-outlook.md](https://github.com/v-thepet/powerapps-docs-pr/blob/oneoffs/powerapps-docs/connections/connection-office365-outlook.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powerapps/connections/connection-office365-outlook?branch=pr-en-us-29) |
[powerapps-docs/data-platform-create-entity.md](https://github.com/v-thepet/powerapps-docs-pr/blob/oneoffs/powerapps-docs/data-platform-create-entity.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powerapps/data-platform-create-entity?branch=pr-en-us-29) |
[powerapps-docs/data-platform-intro.md](https://github.com/v-thepet/powerapps-docs-pr/blob/oneoffs/powerapps-docs/data-platform-intro.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powerapps/data-platform-intro?branch=pr-en-us-29) |
[powerapps-docs/data-platform-manage-fields.md](https://github.com/v-thepet/powerapps-docs-pr/blob/oneoffs/powerapps-docs/data-platform-manage-fields.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powerapps/data-platform-manage-fields?branch=pr-en-us-29) |
[powerapps-docs/embed-apps-dev.md](https://github.com/v-thepet/powerapps-docs-pr/blob/oneoffs/powerapps-docs/embed-apps-dev.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powerapps/embed-apps-dev?branch=pr-en-us-29) |
[powerapps-docs/gateway-reference.md](https://github.com/v-thepet/powerapps-docs-pr/blob/oneoffs/powerapps-docs/gateway-reference.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powerapps/gateway-reference?branch=pr-en-us-29) |
[powerapps-docs/regions-overview.md](https://github.com/v-thepet/powerapps-docs-pr/blob/oneoffs/powerapps-docs/regions-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powerapps/regions-overview?branch=pr-en-us-29) |
[powerapps-docs/signup-for-powerapps.md](https://github.com/v-thepet/powerapps-docs-pr/blob/oneoffs/powerapps-docs/signup-for-powerapps.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powerapps/signup-for-powerapps?branch=pr-en-us-29) |
[powerapps-docs/working-with-variables.md](https://github.com/v-thepet/powerapps-docs-pr/blob/oneoffs/powerapps-docs/working-with-variables.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powerapps/working-with-variables?branch=pr-en-us-29) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C11%5C7%5Cf1db111a-32d3-53c6-e514-6b2c2a103d47%5CPullRequest%5C201711071917135198-29%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=%2F95bOfVbcI0hqfe7qWjtGIZIP5ULc%2BB3FX81nnJ8K40%3D&st=2017-11-07T19%3A13%3A54Z&se=2017-12-08T19%3A18%3A54Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by sudeepku** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[powerapps-docs/connections/connection-office365-outlook.md](https://github.com/v-thepet/powerapps-docs-pr/blob/oneoffs/powerapps-docs/connections/connection-office365-outlook.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powerapps/connections/connection-office365-outlook?branch=pr-en-us-29) |
[powerapps-docs/data-platform-create-entity.md](https://github.com/v-thepet/powerapps-docs-pr/blob/oneoffs/powerapps-docs/data-platform-create-entity.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powerapps/data-platform-create-entity?branch=pr-en-us-29) |
[powerapps-docs/data-platform-intro.md](https://github.com/v-thepet/powerapps-docs-pr/blob/oneoffs/powerapps-docs/data-platform-intro.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powerapps/data-platform-intro?branch=pr-en-us-29) |
[powerapps-docs/data-platform-manage-fields.md](https://github.com/v-thepet/powerapps-docs-pr/blob/oneoffs/powerapps-docs/data-platform-manage-fields.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powerapps/data-platform-manage-fields?branch=pr-en-us-29) |
[powerapps-docs/embed-apps-dev.md](https://github.com/v-thepet/powerapps-docs-pr/blob/oneoffs/powerapps-docs/embed-apps-dev.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powerapps/embed-apps-dev?branch=pr-en-us-29) |
[powerapps-docs/gateway-reference.md](https://github.com/v-thepet/powerapps-docs-pr/blob/oneoffs/powerapps-docs/gateway-reference.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powerapps/gateway-reference?branch=pr-en-us-29) |
[powerapps-docs/regions-overview.md](https://github.com/v-thepet/powerapps-docs-pr/blob/oneoffs/powerapps-docs/regions-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powerapps/regions-overview?branch=pr-en-us-29) |
[powerapps-docs/signup-for-powerapps.md](https://github.com/v-thepet/powerapps-docs-pr/blob/oneoffs/powerapps-docs/signup-for-powerapps.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powerapps/signup-for-powerapps?branch=pr-en-us-29) |
[powerapps-docs/working-with-variables.md](https://github.com/v-thepet/powerapps-docs-pr/blob/oneoffs/powerapps-docs/working-with-variables.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powerapps/working-with-variables?branch=pr-en-us-29) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C11%5C7%5Cf1db111a-32d3-53c6-e514-6b2c2a103d47%5CPullRequest%5C201711071956279158-29%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=0Nwuw8wO9lHHeHLC2dfmBB9KiBD9y%2BHRuSYWRMSbPnQ%3D&st=2017-11-07T19%3A52%3A46Z&se=2017-12-08T19%3A57%3A46Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by sudeepku** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[powerapps-docs/connections/connection-office365-outlook.md](https://github.com/v-thepet/powerapps-docs-pr/blob/oneoffs/powerapps-docs/connections/connection-office365-outlook.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powerapps/connections/connection-office365-outlook?branch=pr-en-us-29) |
[powerapps-docs/data-platform-create-entity.md](https://github.com/v-thepet/powerapps-docs-pr/blob/oneoffs/powerapps-docs/data-platform-create-entity.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powerapps/data-platform-create-entity?branch=pr-en-us-29) |
[powerapps-docs/data-platform-intro.md](https://github.com/v-thepet/powerapps-docs-pr/blob/oneoffs/powerapps-docs/data-platform-intro.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powerapps/data-platform-intro?branch=pr-en-us-29) |
[powerapps-docs/data-platform-manage-fields.md](https://github.com/v-thepet/powerapps-docs-pr/blob/oneoffs/powerapps-docs/data-platform-manage-fields.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powerapps/data-platform-manage-fields?branch=pr-en-us-29) |
[powerapps-docs/embed-apps-dev.md](https://github.com/v-thepet/powerapps-docs-pr/blob/oneoffs/powerapps-docs/embed-apps-dev.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powerapps/embed-apps-dev?branch=pr-en-us-29) |
[powerapps-docs/gateway-reference.md](https://github.com/v-thepet/powerapps-docs-pr/blob/oneoffs/powerapps-docs/gateway-reference.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powerapps/gateway-reference?branch=pr-en-us-29) |
[powerapps-docs/regions-overview.md](https://github.com/v-thepet/powerapps-docs-pr/blob/oneoffs/powerapps-docs/regions-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powerapps/regions-overview?branch=pr-en-us-29) |
[powerapps-docs/signup-for-powerapps.md](https://github.com/v-thepet/powerapps-docs-pr/blob/oneoffs/powerapps-docs/signup-for-powerapps.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powerapps/signup-for-powerapps?branch=pr-en-us-29) |
[powerapps-docs/working-with-variables.md](https://github.com/v-thepet/powerapps-docs-pr/blob/oneoffs/powerapps-docs/working-with-variables.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powerapps/working-with-variables?branch=pr-en-us-29) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C11%5C7%5Cf1db111a-32d3-53c6-e514-6b2c2a103d47%5CPullRequest%5C201711072019333434-29%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=nsdTSoo2o2DIjWThDQdWAQ5kmAiTGg76d%2BLPqeAXpQQ%3D&st=2017-11-07T20%3A17%3A36Z&se=2017-12-08T20%3A22%3A36Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by v-thepet** [comment]
#sign-off - removes video call and replaces alerts & a couple other issues in the newly migrated files.

**Pull request merged**
