### PR TITLE
12_1_ML_edits

### PR DESCRIPTION
**Pull request by mackenzielyng**

### CODE REVIEW

**Comment by sudeepku** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[powerapps-docs/webinars-listing.md](https://github.com/mackenzielyng/powerapps-docs-pr/blob/master/powerapps-docs/webinars-listing.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powerapps/webinars-listing?branch=pr-en-us-84) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C12%5C1%5Cf1db111a-32d3-53c6-e514-6b2c2a103d47%5CPullRequest%5C201712012247199356-84%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=dRnCEs4%2FdcfOzH6LkWqxUHTL6J%2FTJ64n8CET24wZjjc%3D&st=2017-12-01T22%3A43%3A25Z&se=2018-01-01T22%3A48%3A25Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by PRMerger19** [comment]
## PRMerger Results
 | Issue | Resolution |
 --- | --- | 
 File Change Percent | This PR contains file(s) with more than 20% file change.

**Comment by sudeepku** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[powerapps-docs/webinars-listing.md](https://github.com/mackenzielyng/powerapps-docs-pr/blob/master/powerapps-docs/webinars-listing.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powerapps/webinars-listing?branch=pr-en-us-84) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C12%5C1%5Cf1db111a-32d3-53c6-e514-6b2c2a103d47%5CPullRequest%5C201712012304466840-84%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=qzmWG5Qgr2%2Buh%2B1a97nabxR4x2uDOjDjXiEriMzS9lQ%3D&st=2017-12-01T23%3A00%3A48Z&se=2018-01-01T23%3A05%3A48Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by PRMerger8** [comment]
## PRMerger Results
 | Issue | Resolution |
 --- | --- | 
 File Change Percent | This PR contains file(s) with more than 20% file change.

**Comment by mackenzielyng** [comment]
#signoff

**Comment by mgblythe** [comment]
@mackenzielyng -- Hi Mackenzie, the #sign off needs to have a dash between sign and off to trigger our automation. Otherwise, you're good to go

**Comment by mackenzielyng** [comment]
@mgblythe noted! Updated below:

#sign-off

**Pull request merged**
