### PR TITLE
getting-started (added an updated screenshot)

### PR DESCRIPTION
**Pull request by SKjerland**

### CODE REVIEW

**Comment by sudeepku** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[powerapps-docs/getting-started.md](https://github.com/SKjerland/powerapps-docs-pr/blob/intro/powerapps-docs/getting-started.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powerapps/getting-started?branch=pr-en-us-85) |
[powerapps-docs/media/getting-started/sample-apps.png](https://github.com/SKjerland/powerapps-docs-pr/blob/intro/powerapps-docs/media/getting-started/sample-apps.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powerapps/getting-started?branch=pr-en-us-85) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C12%5C4%5Cf1db111a-32d3-53c6-e514-6b2c2a103d47%5CPullRequest%5C201712042220046713-85%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=V0w8v3hrF88sqcz32Up0%2Bql1F4SaNaQ2Eah3I5FquhM%3D&st=2017-12-04T22%3A17%3A20Z&se=2018-01-04T22%3A22%3A20Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by PRMerger18** [comment]
## PRMerger Results
 | Issue | Resolution |
 --- | --- | 
 Added or Deleted File(s) | This PR contains added or deleted file(s). 
 Image File | This PR contains an image file(s).

**Comment by sudeepku** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[powerapps-docs/getting-started.md](https://github.com/SKjerland/powerapps-docs-pr/blob/intro/powerapps-docs/getting-started.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powerapps/getting-started?branch=pr-en-us-85) |
[powerapps-docs/media/getting-started/sample-apps.png](https://github.com/SKjerland/powerapps-docs-pr/blob/intro/powerapps-docs/media/getting-started/sample-apps.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powerapps/getting-started?branch=pr-en-us-85) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C12%5C4%5Cf1db111a-32d3-53c6-e514-6b2c2a103d47%5CPullRequest%5C201712042227397149-85%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=anelmYwz9j7RSlfZJ%2F6et9SwmM3ZY0qK%2BcpulEwIqV0%3D&st=2017-12-04T22%3A23%3A51Z&se=2018-01-04T22%3A28%3A51Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by PRMerger16** [comment]
## PRMerger Results
 | Issue | Resolution |
 --- | --- | 
 Image File | This PR contains an image file(s). 
 Added or Deleted File(s) | This PR contains added or deleted file(s).

**Comment by SKjerland** [comment]
Can merge at any time - not part of a release

**Comment by SKjerland** [comment]
#sign-off

**Pull request merged**
