### PR TITLE
Update README to follow new template

### PR DESCRIPTION
**Pull request by mgblythe**

### CODE REVIEW

**Comment by PRMerger7** [comment]
## PRMerger Results
 | Issue | Resolution |
 --- | --- | 
 Repository root file |  This pull request contains a file submitted to the root of the repository. This is not allowed; please remove this file from the pull request. 
 File Change Percent | This PR contains file(s) with more than 20% file change.

**Comment by mgblythe** [comment]
#sign-off 

Let me know if I should merge this b/c it's a file at the root.

**Comment by v-shils** [comment]
Hi @mgblythe,

[Contributor guide](https://review.docs.microsoft.com/en-us/help/contribute/contribute-how-to-write-pull-request-quality-criteria?branch=master) says... 
"Pull requests that change a configuration file in the root folder must be reviewed and merged by the repo administrator." 

Thanks,
#hold-off

**Comment by mgblythe** [comment]
@v-shils -- I'm the repo admin, so I will do this :smiley:

**Comment by mgblythe** [comment]
#sign-off

**Pull request merged**
