### PR TITLE
test fixes

### PR DESCRIPTION
**Pull request by v-thepet**

### CODE REVIEW

**Comment by sudeepku** [comment]
### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[powerapps-docs/includes/app-customization-requirements.md](https://github.com/v-thepet/powerapps-docs-pr/blob/test-fixes/powerapps-docs/includes/app-customization-requirements.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/powerapps/add-list-box-drop-down-list-radio-button?branch=pr-en-us-9) | [Details](#user-content-powerapps-docs%2Fincludes%2Fapp-customization-requirements.md)
[powerapps-docs/includes/connection-requirements.md](https://github.com/v-thepet/powerapps-docs-pr/blob/test-fixes/powerapps-docs/includes/connection-requirements.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/powerapps/connections/connection-microsoft-translator?branch=pr-en-us-9) | [Details](#user-content-powerapps-docs%2Fincludes%2Fconnection-requirements.md)
[powerapps-docs/includes/delegation-no-one.md](https://github.com/v-thepet/powerapps-docs-pr/blob/test-fixes/powerapps-docs/includes/delegation-no-one.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/powerapps/functions/function-forall?branch=pr-en-us-9) | [Details](#user-content-powerapps-docs%2Fincludes%2Fdelegation-no-one.md)
[powerapps-docs/includes/delegation-no.md](https://github.com/v-thepet/powerapps-docs-pr/blob/test-fixes/powerapps-docs/includes/delegation-no.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/powerapps/functions/function-update-updateif?branch=pr-en-us-9) | [Details](#user-content-powerapps-docs%2Fincludes%2Fdelegation-no.md)
[powerapps-docs/includes/delegation.md](https://github.com/v-thepet/powerapps-docs-pr/blob/test-fixes/powerapps-docs/includes/delegation.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/powerapps/functions/function-sort?branch=pr-en-us-9) | [Details](#user-content-powerapps-docs%2Fincludes%2Fdelegation.md)
[powerapps-docs/includes/long-items.md](https://github.com/v-thepet/powerapps-docs-pr/blob/test-fixes/powerapps-docs/includes/long-items.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/powerapps/controls/control-drop-down?branch=pr-en-us-9) | [Details](#user-content-powerapps-docs%2Fincludes%2Flong-items.md)
[powerapps-docs/includes/record-scope.md](https://github.com/v-thepet/powerapps-docs-pr/blob/test-fixes/powerapps-docs/includes/record-scope.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/powerapps/functions/function-aggregates?branch=pr-en-us-9) | [Details](#user-content-powerapps-docs%2Fincludes%2Frecord-scope.md)
[powerapps-docs/app-analytics.md](https://github.com/v-thepet/powerapps-docs-pr/blob/test-fixes/powerapps-docs/app-analytics.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powerapps/app-analytics?branch=pr-en-us-9) |
[powerapps-docs/controls/control-screen.md](https://github.com/v-thepet/powerapps-docs-pr/blob/test-fixes/powerapps-docs/controls/control-screen.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powerapps/controls/control-screen?branch=pr-en-us-9) |
[powerapps-docs/data-platform-create-entity.md](https://github.com/v-thepet/powerapps-docs-pr/blob/test-fixes/powerapps-docs/data-platform-create-entity.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powerapps/data-platform-create-entity?branch=pr-en-us-9) |
[powerapps-docs/data-platform-intro.md](https://github.com/v-thepet/powerapps-docs-pr/blob/test-fixes/powerapps-docs/data-platform-intro.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powerapps/data-platform-intro?branch=pr-en-us-9) |
[powerapps-docs/data-platform-manage-fields.md](https://github.com/v-thepet/powerapps-docs-pr/blob/test-fixes/powerapps-docs/data-platform-manage-fields.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powerapps/data-platform-manage-fields?branch=pr-en-us-9) |
[powerapps-docs/functions/function-set.md](https://github.com/v-thepet/powerapps-docs-pr/blob/test-fixes/powerapps-docs/functions/function-set.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powerapps/functions/function-set?branch=pr-en-us-9) |
[powerapps-docs/functions/function-startswith.md](https://github.com/v-thepet/powerapps-docs-pr/blob/test-fixes/powerapps-docs/functions/function-startswith.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powerapps/functions/function-startswith?branch=pr-en-us-9) |
[powerapps-docs/functions/function-updatecontext.md](https://github.com/v-thepet/powerapps-docs-pr/blob/test-fixes/powerapps-docs/functions/function-updatecontext.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powerapps/functions/function-updatecontext?branch=pr-en-us-9) |

<a name="powerapps-docs%2Fincludes%2Fapp-customization-requirements.md"></a>
### [powerapps-docs/includes/app-customization-requirements.md](https://github.com/v-thepet/powerapps-docs-pr/blob/test-fixes/powerapps-docs/includes/app-customization-requirements.md)
 - **Line 2**: **[Warning]** Invalid file link:(~/includes/signup-for-powerapps.md).
 - **Line 2**: **[Warning]** Invalid file link:(~/includes/signup-for-powerapps.md).
 - **Line 2**: **[Warning]** Invalid file link:(~/includes/signup-for-powerapps.md).
 - **Line 2**: **[Warning]** Invalid file link:(~/includes/signup-for-powerapps.md).
 - **Line 3**: **[Warning]** Invalid file link:(~/includes/get-started-create-from-data.md).
 - **Line 3**: **[Warning]** Invalid file link:(~/includes/get-started-create-from-blank.md).
 - **Line 3**: **[Warning]** Invalid file link:(~/includes/get-started-test-drive.md).
 - **Line 3**: **[Warning]** Invalid file link:(~/includes/get-started-create-from-data.md).
 - **Line 3**: **[Warning]** Invalid file link:(~/includes/get-started-create-from-blank.md).
 - **Line 3**: **[Warning]** Invalid file link:(~/includes/get-started-test-drive.md).
 - **Line 3**: **[Warning]** Invalid file link:(~/includes/get-started-create-from-data.md).
 - **Line 3**: **[Warning]** Invalid file link:(~/includes/get-started-create-from-blank.md).
 - **Line 3**: **[Warning]** Invalid file link:(~/includes/get-started-test-drive.md).
 - **Line 3**: **[Warning]** Invalid file link:(~/includes/get-started-create-from-data.md).
 - **Line 3**: **[Warning]** Invalid file link:(~/includes/get-started-create-from-blank.md).
 - **Line 3**: **[Warning]** Invalid file link:(~/includes/get-started-test-drive.md).
 - **Line 4**: **[Warning]** Invalid file link:(~/includes/add-configure-controls.md).
 - **Line 4**: **[Warning]** Invalid file link:(~/includes/add-configure-controls.md).
 - **Line 4**: **[Warning]** Invalid file link:(~/includes/add-configure-controls.md).
 - **Line 4**: **[Warning]** Invalid file link:(~/includes/add-configure-controls.md).

<a name="powerapps-docs%2Fincludes%2Fconnection-requirements.md"></a>
### [powerapps-docs/includes/connection-requirements.md](https://github.com/v-thepet/powerapps-docs-pr/blob/test-fixes/powerapps-docs/includes/connection-requirements.md)
 - **Line 3**: **[Warning]** Invalid file link:(~/includes/add-manage-connections.md).
 - **Line 3**: **[Warning]** Invalid file link:(~/includes/add-manage-connections.md).
 - **Line 3**: **[Warning]** Invalid file link:(~/includes/add-manage-connections.md).
 - **Line 3**: **[Warning]** Invalid file link:(~/includes/add-manage-connections.md).
 - **Line 3**: **[Warning]** Invalid file link:(~/includes/add-manage-connections.md).
 - **Line 4**: **[Warning]** Invalid file link:(~/includes/get-started-create-from-data.md).
 - **Line 4**: **[Warning]** Invalid file link:(~/includes/get-started-create-from-blank.md).
 - **Line 4**: **[Warning]** Invalid file link:(~/includes/get-started-test-drive.md).
 - **Line 4**: **[Warning]** Invalid file link:(~/includes/get-started-create-from-data.md).
 - **Line 4**: **[Warning]** Invalid file link:(~/includes/get-started-create-from-blank.md).
 - **Line 4**: **[Warning]** Invalid file link:(~/includes/get-started-test-drive.md).
 - **Line 4**: **[Warning]** Invalid file link:(~/includes/get-started-create-from-data.md).
 - **Line 4**: **[Warning]** Invalid file link:(~/includes/get-started-create-from-blank.md).
 - **Line 4**: **[Warning]** Invalid file link:(~/includes/get-started-test-drive.md).
 - **Line 4**: **[Warning]** Invalid file link:(~/includes/get-started-create-from-data.md).
 - **Line 4**: **[Warning]** Invalid file link:(~/includes/get-started-create-from-blank.md).
 - **Line 4**: **[Warning]** Invalid file link:(~/includes/get-started-test-drive.md).
 - **Line 4**: **[Warning]** Invalid file link:(~/includes/get-started-create-from-data.md).
 - **Line 4**: **[Warning]** Invalid file link:(~/includes/get-started-create-from-blank.md).
 - **Line 4**: **[Warning]** Invalid file link:(~/includes/get-started-test-drive.md).

<a name="powerapps-docs%2Fincludes%2Fdelegation-no-one.md"></a>
### [powerapps-docs/includes/delegation-no-one.md](https://github.com/v-thepet/powerapps-docs-pr/blob/test-fixes/powerapps-docs/includes/delegation-no-one.md)
 - **Line 2**: **[Warning]** Invalid file link:(~/includes/delegation-overview.md).

<a name="powerapps-docs%2Fincludes%2Fdelegation-no.md"></a>
### [powerapps-docs/includes/delegation-no.md](https://github.com/v-thepet/powerapps-docs-pr/blob/test-fixes/powerapps-docs/includes/delegation-no.md)
 - **Line 2**: **[Warning]** Invalid file link:(~/includes/delegation-overview.md).
 - **Line 2**: **[Warning]** Invalid file link:(~/includes/delegation-overview.md).
 - **Line 2**: **[Warning]** Invalid file link:(~/includes/delegation-overview.md).
 - **Line 2**: **[Warning]** Invalid file link:(~/includes/delegation-overview.md).
 - **Line 2**: **[Warning]** Invalid file link:(~/includes/delegation-overview.md).

<a name="powerapps-docs%2Fincludes%2Fdelegation.md"></a>
### [powerapps-docs/includes/delegation.md](https://github.com/v-thepet/powerapps-docs-pr/blob/test-fixes/powerapps-docs/includes/delegation.md)
 - **Line 2**: **[Warning]** Invalid file link:(~/includes/controls/control-gallery.md).
 - **Line 2**: **[Warning]** Invalid file link:(~/includes/controls/control-gallery.md).
 - **Line 4**: **[Warning]** Invalid file link:(~/includes/delegation-list.md).
 - **Line 4**: **[Warning]** Invalid file link:(~/includes/delegation-list.md).
 - **Line 6**: **[Warning]** Invalid file link:(~/includes/controls/control-gallery.md).
 - **Line 6**: **[Warning]** Invalid file link:(~/includes/controls/control-gallery.md).
 - **Line 8**: **[Warning]** Invalid file link:(~/includes/delegation-overview.md).
 - **Line 8**: **[Warning]** Invalid file link:(~/includes/delegation-overview.md).

<a name="powerapps-docs%2Fincludes%2Flong-items.md"></a>
### [powerapps-docs/includes/long-items.md](https://github.com/v-thepet/powerapps-docs-pr/blob/test-fixes/powerapps-docs/includes/long-items.md)
 - **Line 1**: **[Warning]** Invalid file link:(~/includes/controls/properties-core.md).
 - **Line 1**: **[Warning]** Invalid file link:(~/includes/controls/properties-core.md).
 - **Line 1**: **[Warning]** Invalid file link:(~/includes/controls/properties-core.md).

<a name="powerapps-docs%2Fincludes%2Frecord-scope.md"></a>
### [powerapps-docs/includes/record-scope.md](https://github.com/v-thepet/powerapps-docs-pr/blob/test-fixes/powerapps-docs/includes/record-scope.md)
 - **Line 1**: **[Warning]** Invalid file link:(~/includes/working-with-tables.md#record-scope).
 - **Line 1**: **[Warning]** Invalid file link:(~/includes/working-with-tables.md#record-scope).
 - **Line 1**: **[Warning]** Invalid file link:(~/includes/working-with-tables.md#record-scope).
 - **Line 1**: **[Warning]** Invalid file link:(~/includes/working-with-tables.md#record-scope).
 - **Line 1**: **[Warning]** Invalid file link:(~/includes/working-with-tables.md#record-scope).
 - **Line 1**: **[Warning]** Invalid file link:(~/includes/working-with-tables.md#record-scope).
 - **Line 1**: **[Warning]** Invalid file link:(~/includes/working-with-tables.md#record-scope).

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C10%5C28%5Cf1db111a-32d3-53c6-e514-6b2c2a103d47%5CPullRequest%5C201710280233389413-9%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=bw%2FehIpkXpbM2sZEQsHaeOhC5fgbzI88FaCtRcOKGFI%3D&st=2017-10-28T02%3A32%3A12Z&se=2017-11-28T02%3A37%3A12Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by sudeepku** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[powerapps-docs/app-analytics.md](https://github.com/v-thepet/powerapps-docs-pr/blob/test-fixes/powerapps-docs/app-analytics.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powerapps/app-analytics?branch=pr-en-us-9) |
[powerapps-docs/controls/control-screen.md](https://github.com/v-thepet/powerapps-docs-pr/blob/test-fixes/powerapps-docs/controls/control-screen.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powerapps/controls/control-screen?branch=pr-en-us-9) |
[powerapps-docs/data-platform-create-entity.md](https://github.com/v-thepet/powerapps-docs-pr/blob/test-fixes/powerapps-docs/data-platform-create-entity.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powerapps/data-platform-create-entity?branch=pr-en-us-9) |
[powerapps-docs/data-platform-intro.md](https://github.com/v-thepet/powerapps-docs-pr/blob/test-fixes/powerapps-docs/data-platform-intro.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powerapps/data-platform-intro?branch=pr-en-us-9) |
[powerapps-docs/data-platform-manage-fields.md](https://github.com/v-thepet/powerapps-docs-pr/blob/test-fixes/powerapps-docs/data-platform-manage-fields.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powerapps/data-platform-manage-fields?branch=pr-en-us-9) |
[powerapps-docs/functions/function-set.md](https://github.com/v-thepet/powerapps-docs-pr/blob/test-fixes/powerapps-docs/functions/function-set.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powerapps/functions/function-set?branch=pr-en-us-9) |
[powerapps-docs/functions/function-startswith.md](https://github.com/v-thepet/powerapps-docs-pr/blob/test-fixes/powerapps-docs/functions/function-startswith.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powerapps/functions/function-startswith?branch=pr-en-us-9) |
[powerapps-docs/functions/function-updatecontext.md](https://github.com/v-thepet/powerapps-docs-pr/blob/test-fixes/powerapps-docs/functions/function-updatecontext.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powerapps/functions/function-updatecontext?branch=pr-en-us-9) |
[powerapps-docs/includes/app-customization-requirements.md](https://github.com/v-thepet/powerapps-docs-pr/blob/test-fixes/powerapps-docs/includes/app-customization-requirements.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powerapps/add-list-box-drop-down-list-radio-button?branch=pr-en-us-9) |
[powerapps-docs/includes/connection-requirements.md](https://github.com/v-thepet/powerapps-docs-pr/blob/test-fixes/powerapps-docs/includes/connection-requirements.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powerapps/connections/connection-microsoft-translator?branch=pr-en-us-9) |
[powerapps-docs/includes/delegation-no-one.md](https://github.com/v-thepet/powerapps-docs-pr/blob/test-fixes/powerapps-docs/includes/delegation-no-one.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powerapps/functions/function-forall?branch=pr-en-us-9) |
[powerapps-docs/includes/delegation-no.md](https://github.com/v-thepet/powerapps-docs-pr/blob/test-fixes/powerapps-docs/includes/delegation-no.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powerapps/functions/function-update-updateif?branch=pr-en-us-9) |
[powerapps-docs/includes/delegation.md](https://github.com/v-thepet/powerapps-docs-pr/blob/test-fixes/powerapps-docs/includes/delegation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powerapps/functions/function-sort?branch=pr-en-us-9) |
[powerapps-docs/includes/long-items.md](https://github.com/v-thepet/powerapps-docs-pr/blob/test-fixes/powerapps-docs/includes/long-items.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powerapps/controls/control-drop-down?branch=pr-en-us-9) |
[powerapps-docs/includes/record-scope.md](https://github.com/v-thepet/powerapps-docs-pr/blob/test-fixes/powerapps-docs/includes/record-scope.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powerapps/functions/function-aggregates?branch=pr-en-us-9) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C10%5C28%5Cf1db111a-32d3-53c6-e514-6b2c2a103d47%5CPullRequest%5C201710280327175841-9%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=lQZM8HiFg%2FRMP6Gyk9ypsbD2sLd5BfvC3hFmKby2t2g%3D&st=2017-10-28T03%3A23%3A17Z&se=2017-11-28T03%3A28%3A17Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by sudeepku** [comment]
### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[powerapps-docs/release-notes.md](https://github.com/v-thepet/powerapps-docs-pr/blob/test-fixes/powerapps-docs/release-notes.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/powerapps/release-notes?branch=pr-en-us-9) | [Details](#user-content-powerapps-docs%2Frelease-notes.md)
[powerapps-docs/app-analytics.md](https://github.com/v-thepet/powerapps-docs-pr/blob/test-fixes/powerapps-docs/app-analytics.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powerapps/app-analytics?branch=pr-en-us-9) |
[powerapps-docs/controls/control-screen.md](https://github.com/v-thepet/powerapps-docs-pr/blob/test-fixes/powerapps-docs/controls/control-screen.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powerapps/controls/control-screen?branch=pr-en-us-9) |
[powerapps-docs/data-platform-create-entity.md](https://github.com/v-thepet/powerapps-docs-pr/blob/test-fixes/powerapps-docs/data-platform-create-entity.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powerapps/data-platform-create-entity?branch=pr-en-us-9) |
[powerapps-docs/data-platform-intro.md](https://github.com/v-thepet/powerapps-docs-pr/blob/test-fixes/powerapps-docs/data-platform-intro.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powerapps/data-platform-intro?branch=pr-en-us-9) |
[powerapps-docs/data-platform-manage-fields.md](https://github.com/v-thepet/powerapps-docs-pr/blob/test-fixes/powerapps-docs/data-platform-manage-fields.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powerapps/data-platform-manage-fields?branch=pr-en-us-9) |
[powerapps-docs/functions/function-set.md](https://github.com/v-thepet/powerapps-docs-pr/blob/test-fixes/powerapps-docs/functions/function-set.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powerapps/functions/function-set?branch=pr-en-us-9) |
[powerapps-docs/functions/function-startswith.md](https://github.com/v-thepet/powerapps-docs-pr/blob/test-fixes/powerapps-docs/functions/function-startswith.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powerapps/functions/function-startswith?branch=pr-en-us-9) |
[powerapps-docs/functions/function-updatecontext.md](https://github.com/v-thepet/powerapps-docs-pr/blob/test-fixes/powerapps-docs/functions/function-updatecontext.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powerapps/functions/function-updatecontext?branch=pr-en-us-9) |
[powerapps-docs/includes/app-customization-requirements.md](https://github.com/v-thepet/powerapps-docs-pr/blob/test-fixes/powerapps-docs/includes/app-customization-requirements.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powerapps/show-current-user?branch=pr-en-us-9) |
[powerapps-docs/includes/connection-requirements.md](https://github.com/v-thepet/powerapps-docs-pr/blob/test-fixes/powerapps-docs/includes/connection-requirements.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powerapps/connections/connection-twitter?branch=pr-en-us-9) |
[powerapps-docs/includes/delegation-no-one.md](https://github.com/v-thepet/powerapps-docs-pr/blob/test-fixes/powerapps-docs/includes/delegation-no-one.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powerapps/functions/function-forall?branch=pr-en-us-9) |
[powerapps-docs/includes/delegation-no.md](https://github.com/v-thepet/powerapps-docs-pr/blob/test-fixes/powerapps-docs/includes/delegation-no.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powerapps/functions/function-update-updateif?branch=pr-en-us-9) |
[powerapps-docs/includes/delegation.md](https://github.com/v-thepet/powerapps-docs-pr/blob/test-fixes/powerapps-docs/includes/delegation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powerapps/functions/function-filter-lookup?branch=pr-en-us-9) |
[powerapps-docs/includes/long-items.md](https://github.com/v-thepet/powerapps-docs-pr/blob/test-fixes/powerapps-docs/includes/long-items.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powerapps/controls/control-radio?branch=pr-en-us-9) |
[powerapps-docs/includes/record-scope.md](https://github.com/v-thepet/powerapps-docs-pr/blob/test-fixes/powerapps-docs/includes/record-scope.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powerapps/functions/function-forall?branch=pr-en-us-9) |
[powerapps-docs/working-with-variables.md](https://github.com/v-thepet/powerapps-docs-pr/blob/test-fixes/powerapps-docs/working-with-variables.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powerapps/working-with-variables?branch=pr-en-us-9) |

<a name="powerapps-docs%2Frelease-notes.md"></a>
### [powerapps-docs/release-notes.md](https://github.com/v-thepet/powerapps-docs-pr/blob/test-fixes/powerapps-docs/release-notes.md)
 - **Line 125**: **[Warning]** Invalid file link:(~/properties-accessibility.md).

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C10%5C28%5Cf1db111a-32d3-53c6-e514-6b2c2a103d47%5CPullRequest%5C201710280348016404-9%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=5R0tJT99KnhdSnRcJvwzJy4VUmTs75pfLhbEePjyD8s%3D&st=2017-10-28T03%3A44%3A01Z&se=2017-11-28T03%3A49%3A01Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by sudeepku** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[powerapps-docs/app-analytics.md](https://github.com/v-thepet/powerapps-docs-pr/blob/test-fixes/powerapps-docs/app-analytics.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powerapps/app-analytics?branch=pr-en-us-9) |
[powerapps-docs/controls/control-screen.md](https://github.com/v-thepet/powerapps-docs-pr/blob/test-fixes/powerapps-docs/controls/control-screen.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powerapps/controls/control-screen?branch=pr-en-us-9) |
[powerapps-docs/data-platform-create-entity.md](https://github.com/v-thepet/powerapps-docs-pr/blob/test-fixes/powerapps-docs/data-platform-create-entity.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powerapps/data-platform-create-entity?branch=pr-en-us-9) |
[powerapps-docs/data-platform-intro.md](https://github.com/v-thepet/powerapps-docs-pr/blob/test-fixes/powerapps-docs/data-platform-intro.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powerapps/data-platform-intro?branch=pr-en-us-9) |
[powerapps-docs/data-platform-manage-fields.md](https://github.com/v-thepet/powerapps-docs-pr/blob/test-fixes/powerapps-docs/data-platform-manage-fields.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powerapps/data-platform-manage-fields?branch=pr-en-us-9) |
[powerapps-docs/functions/function-set.md](https://github.com/v-thepet/powerapps-docs-pr/blob/test-fixes/powerapps-docs/functions/function-set.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powerapps/functions/function-set?branch=pr-en-us-9) |
[powerapps-docs/functions/function-startswith.md](https://github.com/v-thepet/powerapps-docs-pr/blob/test-fixes/powerapps-docs/functions/function-startswith.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powerapps/functions/function-startswith?branch=pr-en-us-9) |
[powerapps-docs/functions/function-updatecontext.md](https://github.com/v-thepet/powerapps-docs-pr/blob/test-fixes/powerapps-docs/functions/function-updatecontext.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powerapps/functions/function-updatecontext?branch=pr-en-us-9) |
[powerapps-docs/includes/app-customization-requirements.md](https://github.com/v-thepet/powerapps-docs-pr/blob/test-fixes/powerapps-docs/includes/app-customization-requirements.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powerapps/add-list-box-drop-down-list-radio-button?branch=pr-en-us-9) |
[powerapps-docs/includes/connection-requirements.md](https://github.com/v-thepet/powerapps-docs-pr/blob/test-fixes/powerapps-docs/includes/connection-requirements.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powerapps/connections/connection-microsoft-translator?branch=pr-en-us-9) |
[powerapps-docs/includes/delegation-no-one.md](https://github.com/v-thepet/powerapps-docs-pr/blob/test-fixes/powerapps-docs/includes/delegation-no-one.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powerapps/functions/function-forall?branch=pr-en-us-9) |
[powerapps-docs/includes/delegation-no.md](https://github.com/v-thepet/powerapps-docs-pr/blob/test-fixes/powerapps-docs/includes/delegation-no.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powerapps/functions/function-update-updateif?branch=pr-en-us-9) |
[powerapps-docs/includes/delegation.md](https://github.com/v-thepet/powerapps-docs-pr/blob/test-fixes/powerapps-docs/includes/delegation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powerapps/functions/function-sort?branch=pr-en-us-9) |
[powerapps-docs/includes/long-items.md](https://github.com/v-thepet/powerapps-docs-pr/blob/test-fixes/powerapps-docs/includes/long-items.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powerapps/controls/control-drop-down?branch=pr-en-us-9) |
[powerapps-docs/includes/record-scope.md](https://github.com/v-thepet/powerapps-docs-pr/blob/test-fixes/powerapps-docs/includes/record-scope.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powerapps/functions/function-aggregates?branch=pr-en-us-9) |
[powerapps-docs/release-notes.md](https://github.com/v-thepet/powerapps-docs-pr/blob/test-fixes/powerapps-docs/release-notes.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powerapps/release-notes?branch=pr-en-us-9) |
[powerapps-docs/working-with-variables.md](https://github.com/v-thepet/powerapps-docs-pr/blob/test-fixes/powerapps-docs/working-with-variables.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powerapps/working-with-variables?branch=pr-en-us-9) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C10%5C28%5Cf1db111a-32d3-53c6-e514-6b2c2a103d47%5CPullRequest%5C201710281756436245-9%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=cl5v%2F3y4D14TbX3XNNlsH5pGHN5cD5Ei7ldt0F2PRwM%3D&st=2017-10-28T17%3A55%3A56Z&se=2017-11-28T18%3A00%3A56Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by v-thepet** [comment]
The only warnings left are in the guided-learning, which I'm not to look at... now closing this one, and starting a new one to test one-pass fix.

**Pull request closed without merging**
